[logger]
level = "warning"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[runner]
magicEnabled = false
